### ISSUE TITLE
Include Binaries

### ISSUE THREAD

**Issue by Nate-Wilkins** [cincuranet/EdmGen2#2]
Could we possibly include releases? 
Have a zip of the current version binaries?

**Comment by cincuranet** [comment]
There's no "official" release. But I can prepare a build. Give me a day or two.

**Comment by Nate-Wilkins** [comment]
@cincuranet Sounds great, thanks!

**Comment by cincuranet** [comment]
I updated the [readme](https://github.com/cincuranet/EdmGen2/blob/master/README.md) with link to automated build. There's no official release status, so I think to get just the latest binaries is fine.

**Comment by Nate-Wilkins** [comment]
:+1: Thanks!
