### ISSUE TITLE
Add ability to maintain designer xml

### ISSUE THREAD

**Issue by Nate-Wilkins** [cincuranet/EdmGen2#3]
I was going to take a look at overwriting an existing edmx file but I'd like to maintain the corresponding designer code that goes along with it. 

Not even sure this is possible or not, I'm assuming so...

**Comment by cincuranet** [comment]
You mean you generate new model from database, but you already have one and you want to keep the `edmx:Designer` section?

**Comment by Nate-Wilkins** [comment]
Exactly.

**Comment by cincuranet** [comment]
I think the easiest way is to use PowerShell and place the node from old file to new file after the generation is done.

**Comment by Nate-Wilkins** [comment]
I think that's the route I'm going to take. We'll see how that goes, thanks!
