### ISSUE TITLE
Where is the code for ConceptualEdmGen.dll?

### ISSUE THREAD

**Issue by knocte** [cincuranet/EdmGen2#6]
I can see the sources for EdmGen2 except for the library ConceptualEdmGen.dll that is included as a blob in the repository here: https://github.com/cincuranet/EdmGen2/blob/master/src/EdmGen2/ConceptualEdmGen.dll

Can you tell where are the sources for this file? Thanks

**Comment by cincuranet** [comment]
There was never a source for this library. It was included as binary from the beginning.

**Comment by knocte** [comment]
Ok fair enough, but who's the author of this library, Microsoft? Is there a place to download it apart from here?

**Comment by cincuranet** [comment]
You can check the [original sources](https://code.msdn.microsoft.com/EdmGen2). It's not working for me me now, though.

**Comment by knocte** [comment]
Yeah, me neither. BTW, does this have support for EFv6? I'm trying to generate .cs files via `EdmGen2 /CodeGen cs MyEdmxFile.edmx` but it just generates an empty `MyEdmxFile.cs` file.

**Comment by cincuranet** [comment]
Off topic for this issue.

**Comment by knocte** [comment]
Are the original sources from Microsoft then?

**Comment by cincuranet** [comment]
Yes, originally the `EdmGen2` was started by Microsoft. Then the community stepped in and this repo is the result.
