### ISSUE TITLE
Can we have same for EDMX6 ?

### ISSUE THREAD

**Issue by sachin369** [cincuranet/EdmGen2#7]
Hello,

This is nice repository and thanks for sharing such a nice code.
right now edmx version and updated and here current code is only available till EDMX version3.

We like latest code to generate edmx version 6 from database

we have database details and connection string to select DB.

Thanks,
Sachin

**Comment by ErikEJ** [comment]
There is no EDMX version 6, the latest (and final?) version is 3.

**Comment by cincuranet** [comment]
Exactly, @ErikEJ is correct. EF 6 is using EDMX v3. And given the architecture of EF 6 isn't going to be fundamentally re-architected, probably, it's the final version (at least for now).
